### ISSUE TITLE
RFC: Package deprecation

### ISSUE THREAD

**Issue by mabar** [apitte/presenter#9]
apitte/presenter was useful bridge to routing contained in nette/application and it also sent response

- Response is now send by Application included in apitte/core.
- Routing to api can be solved with a one-line condition as described [here](https://github.com/apitte/core/blob/master/.docs/index.md#usage-in-combination-with-nette-application)
- Apitte, Symfony Http, Symfony Console, Nette etc. applications are all standalone entrypoints with own way of error handling and they should not be contained in each other. They should be completely separated instead or an front router should choose which one will be used.
- Only issue needed to resolve before deprecation is missing link generator, which will be implemented by apitte/core#94. Once we have a link generator, apitte/presenter is not needed anymore.

**Comment by f3l1x** [comment]
Agreed. Good points. We'll take a look in near future, well you'll take a look ;-)
